### ISSUE TITLE
"Warning: Stan seems to have exited badly" appears when processing data in ERA toolbox 

### ISSUE THREAD

**Issue by pethridge** [peclayson/ERA_Toolbox#11]
I am attempting to process ERP data saved in an .xlsx file using the ERA toolbox.  When I try to process and analyze a new dataset, I receive the following warning:

Warning: Stan seems to have exited badly. 
> In StanFit/process_exit_failure (line 290)
  In StanFit/process_exit (line 170)
  In StanFit>@(src,evnt)process_exit(self,src,evnt)
  In processState/set.exitValue (line 30)
  In processManager.pollTimerStop (line 508)
  In timer/timercb (line 30)
  In timercb (line 13)
  In StanFit/block (line 368)
  In era_computerel (line 364)
  In era_computerelwrap (line 158)
  In era_startproc>era_exec (line 690) 

After the warning appears, the ERA toolbox stops processing the data. 

When I run the analysis with the Verbose Stan Output, the following error appears many times before the warning: 

DSVOaT3CEN14KdAtRcbNtP-output-3.csv: Rejecting initial value:
DSVOaT3CEN14KdAtRcbNtP-output-3.csv:   Error evaluating the log probability at the initial value.

Any ideas what might be causing this problem? 

* ERA Toolbox Version used: 0.4.4
* Matlab Version used: R2015b
* Operating System and Version (desktop or mobile): Windows 7
* CmdStan Version (if applicable): 2.15.0

Thanks in advance!

Paige

**Comment by pethridge** [comment]
Hello again,

I ran the analysis with the same data on a different computer (Mac OS Sierra, v 10.12.5). and received the following errors and warnings. 

Undefined function or variable 'nansum'.

Error in StanFit/block (line 366)
            while nansum(self.loaded) ~= numel(self.loaded)

Error in era_computerel (line 364)
        fit.block();

Error in era_computerelwrap (line 158)
    REL = era_computerel('data',era_data.proc.data,...

Error in era_startproc>era_exec (line 690)
era_data = era_computerelwrap('era_prefs',era_prefs,'era_data',era_data);
 
Error while evaluating DestroyedObject Callback

Warning: Stan seems to have exited badly. 
> In StanFit/process_exit_failure (line 290)
  In StanFit/process_exit (line 170)
  In StanFit>@(src,evnt)process_exit(self,src,evnt)
  In processState/set.exitValue (line 30)
  In processManager.pollTimerStop (line 508)
  In timer/timercb (line 30)
  In timercb (line 13) 
Warning: Stan seems to have exited badly. 
> In StanFit/process_exit_failure (line 290)
  In StanFit/process_exit (line 170)
  In StanFit>@(src,evnt)process_exit(self,src,evnt)
  In processState/set.exitValue (line 30)
  In processManager.pollTimerStop (line 508)
  In timer/timercb (line 30)
  In timercb (line 13) 
Warning: Stan seems to have exited badly. 
> In StanFit/process_exit_failure (line 290)
  In StanFit/process_exit (line 170)
  In StanFit>@(src,evnt)process_exit(self,src,evnt)
  In processState/set.exitValue (line 30)
  In processManager.pollTimerStop (line 508)
  In timer/timercb (line 30)
  In timercb (line 13) 
>>

**Comment by peclayson** [comment]
Good morning,

There are two things I can think of to try. 

I have not checked whether cmdstan v2.15.0 works with the ERA Toolbox. Actually, they just released a newer version (2.16.0). So, I need to check whether anything has changed with cmdstan that might impact how the data need to be run through the toolbox. Additionally, they've also been making many changes to MatlabStan and MatlabProcessManager over the last couple of months. Again, I haven't checked to see whether the toolbox works with the recent changes. I hope to get to checking this out over the next week or so. It's something I've been meaning to do, but other deadlines got in the way.

In the meantime, one thing to try is to roll back to earlier versions of cmdstan,  MatlabStan, and MatlabProcessManager. The current version of the toolbox has been tested with cmdstan v2.14.0,  matlabstan downloaded on 20 Jan 2017, and MatlabStan v 0.5.1 (see [User Manual](https://github.com/peclayson/ERA_Toolbox/blob/57dbf9a1be0ecfa4087c4a5e39b6ef5e56354a0e/documentation/UserManual.pdf)). Admittedly, this would be a bit laborious. If you would like to wait, I can try to get a new version of the toolbox out that works with the most recent, stable versions of the dependents. I should have time to work on this over the coming weekend.

Another thing to try would be to send me a snippet of the data you are trying to run. It's possible that the data are formatted incorrectly, so the toolbox isn't loading it as you'd expect. If your data are formatted as specified in the Preparing Data section of the [User Manual](https://github.com/peclayson/ERA_Toolbox/blob/57dbf9a1be0ecfa4087c4a5e39b6ef5e56354a0e/documentation/UserManual.pdf) then the data are probably formatted correctly.

If you'd like me to try to run the data, you can email me the data at my personal email, which is on page 4 of the [User Manual](https://github.com/peclayson/ERA_Toolbox/blob/57dbf9a1be0ecfa4087c4a5e39b6ef5e56354a0e/documentation/UserManual.pdf).

**Comment by pethridge** [comment]
Hi Peter,

Thanks for your quick response!

I wondered if it might be a version thing. I think I might try
re-installing earlier versions of those programs today or tomorrow. I did
format my data as specified in the Preparing Data section of the user
manual, but I've attached a bit of it to this message, so if you wouldn't
mind double checking that I haven't messed something up, that would be
awesome. One thing I was wondering is that for some subjects they are
missing data on later trials (e.g., there are 20 trials in a condition and
they only have data for 19 of the trials), and those trials are still
listed in the spreadsheet (i.e., there is a row with an ID number for that
trial), but the data cells are empty - would this mess anything up with the
ERA toolbox?

Thanks again,
Paige

**Comment by peclayson** [comment]
Unfortunately, I didn't get the attachment. My guess is that github doesn't support attachments through it's posting service.

But, your hunch is correct. Stan itself cannot handle missing cells in the data. The missing cells need to be stripped before running through the toolbox (and thus Stan). Not including that bit of information is a definite oversight on my part, and I'll be sure to include it in the next release of the manual. I'll also add a little error check to look for missing cells.

Since your data need to be structured in long format with one observation per row, you can simply remove the rows without data. Unfortunately, your data may still not run, because I still need to update comparability with the versions of the dependent software.

Let me know what you find out!

**Comment by pethridge** [comment]
Ok, thanks!

I will reformat the data and see what happens. I'll keep you posted!

Paige

**Comment by pethridge** [comment]
Hi Peter,

Small update: removing the empty cells got me passed the error I was
getting previously, but there's still an error coming up when I try to run
the analyses, so I think there still may be a version problem. I won't have
a chance to reinstall the dependents until after this weekend, but I will
try next week.

Best,
Paige

**Comment by peclayson** [comment]
Progress! Well, this weekend I'm going to tackle compatibility with the new versions of the dependents. Hopefully, if things go smoothly, then you'll just need to update the toolbox :crossed_fingers:

**Comment by pethridge** [comment]
Fingers crossed! 

Have a nice weekend!

**Comment by peclayson** [comment]
I just posted a [new release](https://github.com/peclayson/ERA_Toolbox/releases/tag/v0.4.5) that works with the new versions of the dependents. I actually didn't have to make any changes to the code for inputting the data, so I don't know whether updating the toolbox will fix your problem.

If you'd like to email me a snippet of your data, I could try running it and see what problem I run into. 

Also, the ERA Toolbox has an automatic installation function, if you want to avoid having to update cmdstan to v2.16.0 by hand. I just wanted to let you know in case you installed things manually (as that can be pretty time consuming). If you want to use it, just take all of the dependents off of your Matlab path, and it will ask you whether you would like help installing the dependents when you initiate the toolbox with `era_start` in Matlab. In the future I'll make it smarter so it will update the dependents for you as well.

**Comment by peclayson** [comment]
Although this does not close this issue (we still need to see whether your data run!), I've added some code to check whether there are missing cells in the dataset (see fe3679c127605621f50afb98d3c1e064375c4d73). Now, the user will get a sensical error, rather than having to decipher Stan's error output 😄

**Comment by pethridge** [comment]
Thanks Peter!

I will update the toolbox and try to run it sometime today and see what
happens. I will also email you a bit of the data.

I tried to use the automatic install function when I first downloaded the
toolbox and it didn't work, so I downloaded the dependents separately. I'll
take the dependents out of my Matlab path when I download the updated
toolbox and try the automatic install again.

Paige

**Comment by peclayson** [comment]
Sounds good. I'll look at the file you sent me later this afternoon.

Also, if you run into problems with the automatic installation again, please let me know (it also may be what's getting in the way of Stan running). In my conversations with people, installing the dependents can be the biggest obstacle to using the toolbox. The code I wrote for installing the dependents was meant to address that. Although it works on the Windows and Mac machines I've tested, I'm not surprised that it doesn't work for everyone. It would be great to know what kind of problem you're running into so I can try to fix it, but admittedly it's pretty difficult to troubleshoot a problem I can't replicate... 

Good luck!

**Comment by pethridge** [comment]
Thanks! That's what I did previously too. I have been getting side tracked
by a few things today, but I will let you know as soon as I try to re-run
it.

Paige

**Comment by pethridge** [comment]
It worked!!!!

I downloaded the updated toolbox and removed all of the old stuff from my
matlab path. This time, the automatic install of the dependents worked, and
the data ran fine! It must've been something to do with whatever was
stopping cmd Stan from automatically installing before was also stopping it
from running when I installed the dependents manually.

Thanks so much for your help!

Best,
Paige

**Comment by peclayson** [comment]
Perfect! Glad to hear it.

**Comment by pethridge** [comment]
It's so easy to use when it works! Haha

**Comment by pethridge** [comment]
Hi Peter,

I hope you're well!

I'm trying to re-run some analyses using your toolbox, which I previously
had working fine, and now for some reason that I can't figure out, is not
working anymore.

I tried to analyze the data on a PC (running Windows 7), with version
0.4.4, cmdstan-2.14.0 and I get the following error:

Error using StanModel/set.stan_home (line 305)
Can't parse stan_home. Is it set correctly?

Error in StanModel (line 185)
         self.stan_home = p.Results.stan_home;

Error in stan (line 108)
   model = StanModel();

Error in era_computerel (line 359)
        fit = stan('model_code', stan_in, 'model_name', modelname,...

Error in era_computerelwrap (line 158)
    REL = era_computerel('data',era_data.proc.data,...

Error in era_startproc>era_exec (line 690)
era_data = era_computerelwrap('era_prefs',era_prefs,'era_data',era_data);

Error while evaluating DestroyedObject Callback

Do you have any idea why this might be happening?

Thanks in advance!
Paige

**Comment by peclayson** [comment]
Hi Paige,

Let's see. This looks like a MatlabStan/CmdStan issue. Here are a few things to try. If you have been running your previous analyses on this same machine, my money is on solution one or two... Let me know if they work :)

1. In the 'Installing MatlabStan' section of the  (User Manual)[https://github.com/peclayson/ERA_Toolbox/tree/b07ed991d41c67b939686fb8d60c26154fbcc85e/documentation], can you follow those instructions and verify that the path to your cmdstan directory is properly set in stan_home.m? If it's not set correctly, fixing it should do the trick.

2. Can you verify that you are not trying to save a file with _any_ whitespace anywhere in the path? (I added this error check in at one point, but I don't remember for which version) CmdStan will not run if there is whitespace in the path. 

3. Can you try running the (eight schools)[https://github.com/brian-lau/MatlabStan/wiki/Getting-Started] example? You can just copy and post the code into your command line. If everything is installed correctly, it should run. If this example fails to run, my guess is that you need to re-build your cmdstan. The instructions are also in the (User Manual)[https://github.com/peclayson/ERA_Toolbox/tree/b07ed991d41c67b939686fb8d60c26154fbcc85e/documentation] for doing so. Alternatively, you could try removing the matlab dependents from your path and have the toolbox re-install them in another directory. Whatever you think would be easiest.

Good luck!
Peter

**Comment by pethridge** [comment]
Hi Peter,

Thanks so much for your quick reply! I won't be in my lab until Thursday,
so I will give your suggestions a try then and I'll let you know how it
goes!

Cheers,
Paige

**Comment by pethridge** [comment]
It's working again! (Sorry for the delay)

I think I was just being a dummy. When I went to try your step #1, I
realized I had two ERA dependents folders and matlab didn't like whatever
one I had in my path (for some reason) and when I fixed the path it started
running fine.

Thanks for all of your help!

Paige

**Comment by peclayson** [comment]
I'm glad it's working again. Happy to help :)

Peter

**Comment by pethridge** [comment]
Hi again!

ERA Toolbox working great!... However...

When I run it with one set of data it's excluding a subject and I can't
figure out why. I've run it with a dataset that's almost identical (it's
just a change in the electrode site) and it doesn't exclude anyone, which
is why I'm confused. I've attached the data here. For the file with Cz in
the name, the toolkit doesn't exclude anyone, but for the file with FCav in
the name, it excludes U0_1_100. Any ideas why it might be doing this?

I've run some other data through the toolkit that results in some
exclusions, but at least these were the same across electrode sites, so it
was a bit less confusing. In any case, for what reasons might the toolkit
exclude subjects?

Thanks :)

Paige

**Comment by pethridge** [comment]
Oh man. I figured it out as soon as I sent that email to you. It's because
for that electrode side the min number of trials to get a point estimate of
.70 is 17 and there are only 16 trials for that person.

Please ignore me haha.

Happy holidays!

Paige

**Comment by peclayson** [comment]
Hi Paige,

Ah, man. You beat me to it :) 

Also, I just downloaded your recent Psychophys paper. I'm looking forward to reading it this week.

Happy Holidays!
Peter

**Comment by pethridge** [comment]
Oh, thanks! I hope you like it :)

Paige
