### ISSUE TITLE
unable to estimate reliability for difference scores

### ISSUE THREAD

**Issue by lilianyli** [peclayson/ERA_Toolbox#32]
I got the error message "Only 1 event" even though there were 2 event types. 
It seems that in the "era_startproc" file, the line "if size(era_prefs.proc.inp.whichevents,**1**) < 2" should be "if size(era_prefs.proc.inp.whichevents,**2**) < 2" since era_prefs.proc.inp.whichevents was defined as cell with one row.

## Your Environment

* ERA Toolbox Version used: 0.5.2
* Matlab Version used: 2022a
* Operating System and Version (desktop or mobile): mac OS Ventura 13.2.1 
* CmdStan Version (if applicable): 2.26.1
* MatlabStan Version (if applicable): 2.15.1.0
* MatlabProcessManager Version (if applicable): 0.5.2

**Comment by peclayson** [comment]
I'm so sorry I missed your comment. 

Thank you for letting me know. Can you try downloading from master to see if the problem is fixed? 

Thanks!
Peter

**Comment by lilianyli** [comment]
Yeah it's fixed now! Thanks!
